name: 'UrbanSoochi---Choose-your-ride'
description: 'A custom GitHub Action for UrbanSoochi to choose your ride.'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
  OPENAI_API_KEY:
    description: 'OpenAI API Key'
    required: true
  OPENAI_API_MODEL:
    description: 'OpenAI API Model'
    required: false
    default: 'gpt-4'
  exclude:
    description: 'Patterns to exclude'
    required: false
    default: '**/*.json, **/*.md'
runs:
  using: 'node12'
  main: 'index.js'  # Or your entry point script
