name: UrbanSoochi---Choose-your-ride

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: write
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: UrbanSoochi---Choose-your-ride
        uses: bhaminCoder/UrbanSoochi---Choose-your-ride/.github/workflows/action.yml@master
  # Replace with the actual tag or SHA
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4"  # Optional: defaults to "gpt-4"
          exclude: "**/*.json, **/*.md"  # Optional: exclude patterns separated by commas
